### ISSUE TITLE
VS Code Update

### ISSUE THREAD

**Issue by RochaJG** [codercom/features#194]
**Is your feature request related to a problem? Please describe.**
Some extensions dosen't work properly in actual version of vscode 😢 

**Describe the solution you'd like**
An update to the last version would be very cool! 😀

**Describe alternatives you've considered**
I don't know what's the impasses for that implementation, but I'll acept if it's too hard to do now 😅

**Comment by RochaJG** [comment]
If I can help in any part, maybe making the portability, just tell me and I'll did it with pleasure 😃

**Comment by foresthoffman** [comment]
Hello RochaJG,

Which extensions are not working properly for you?

Cheers,
Forest

**Comment by RochaJG** [comment]
**It's a lot...** 😆 
In this [gist](https://gist.github.com/RochaJG/1b0fe69750d7a53d5b0e4b0ea81224e8) I'm showing all my extensions, and is commented all that is working

**Comment by foresthoffman** [comment]
What errors are you seeing for each of these extensions?

**Comment by RochaJG** [comment]
All of then give me the same error. "Cannot install the extension in that Code version"

**Comment by foresthoffman** [comment]
It seems that you're trying to install extensions that are a few versions ahead of those that are on our marketplace currently. I'll make an internal note of this. In the meantime, try installing the currently available versions, which should be compatible with the current version of Coder.

Thanks for reporting this!

**Comment by RochaJG** [comment]
Awesomel! If I can help you in any thing, just tell me 😃

**Comment by foresthoffman** [comment]
@RochaJG Here's what I've discovered while working on this:

- [Settings Sync (v3.2.5)](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) | https://github.com/shanalikhan/code-settings-sync
- [Dart (v2.23.1)](https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code) | https://github.com/Dart-Code/Dart-Code
- [IntelliSense for CSS, SCSS class names in HTML, Slim and SCSS (v1.5.12)](https://marketplace.visualstudio.com/items?itemName=gencer.html-slim-scss-css-class-completion) | https://github.com/gencer/HTML-Slim-CSS-SCSS-Class-Completion
- [JavaScript (ES6) code snippets (v1.7.2)](https://marketplace.visualstudio.com/items?itemName=xabikos.JavaScriptSnippets) | https://github.com/xabikos/vscode-javascript
- [Mocha Sidebar (v0.20.23)](https://marketplace.visualstudio.com/items?itemName=maty.vscode-mocha-sidebar) | https://github.com/maty21/mocha-sidebar
   - Doesn't work on native VSCode. I get this error notifcation: `Cannot read property 'on' of undefined`.
- [Vue Peek (v1.0.2)](https://marketplace.visualstudio.com/items?itemName=dariofuzinato.vue-peek) | https://github.com/fuzinato/vscode-vue-peek
   - Doesn't work on native VSCode. Does nothing, with no errors.
- [Better Comments (v2.0.3)](https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments) | https://github.com/aaron-bond/better-comments
   - Broken `vscode:prepublish`. Failing due to compile errors. (HEAD:[086c7ea45334a3d545aa8d75f44a2f4ba46ad7ca](https://github.com/aaron-bond/better-comments/commit/086c7ea45334a3d545aa8d75f44a2f4ba46ad7ca))
- ~[Browser Preview (v0.3.1)](https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview) | https://github.com/auchenberg/vscode-browser-preview~
   - Functionality is already provided by cdr.co, and most likely would not work considering the remote nature of our containers. Providing this extension would just cause confusion.

The extensions here, that function properly, have been updated on our internal network, but should be available for public use on coder.com soon. For the extensions that are broken, hopefully the maintainers will push some fixes in the future. When they do, we'll should be able to provide those fixed versions. Therefore, i'll be closing this issue for now.

Thank you for your patience and feedback!
